### ISSUE TITLE
Ruby 2.0 build warnings

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Ruby-Mapnik#31]
```
~/projects/ruby-mapnik[master]$ make
rake compile
mkdir -p tmp/x86_64-darwin12.3.0/ruby_mapnik/2.0.0
cd tmp/x86_64-darwin12.3.0/ruby_mapnik/2.0.0
/usr/local/Cellar/ruby/2.0.0-p195/bin/ruby -I. ../../../../ext/ruby_mapnik/extconf.rb
../../../../ext/ruby_mapnik/extconf.rb:38:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
../../../../ext/ruby_mapnik/extconf.rb:38:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
../../../../ext/ruby_mapnik/extconf.rb:39:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
```

**Comment by gravitystorm** [comment]
These were removed in 2446e6d2bf42754b846cbce046a63e833b89da2d so closing this issue.
