### ISSUE TITLE
Failing tests on Ubuntu 14.04 with Mapnik 2.3.0-pre and ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]

### ISSUE THREAD

**Issue by matkoniecz** [mapnik/Ruby-Mapnik#52]
Versions obtained with `mapnik-config -v` and `ruby -v`

`rake test` gives

```
mateusz@Grisznak:~/Desktop/tmp/Ruby-Mapnik$ rake test
Defaulting gemspec to MIT license.
Call license in hoe spec to change.
install -c tmp/i686-linux/ruby_mapnik/1.9.3/ruby_mapnik.so lib/ruby_mapnik/ruby_mapnik.so
cp tmp/i686-linux/ruby_mapnik/1.9.3/ruby_mapnik.so tmp/i686-linux/stage/lib/ruby_mapnik/ruby_mapnik.so
/usr/bin/ruby1.9.1 -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_mapnik_envelope.rb"; require "test/test_mapnik_font_engine.rb"; require "test/test_mapnik_map.rb"; require "test/test_mapnik_line_symbolizer.rb"; require "test/test_mapnik_color.rb"; require "test/test_mapnik_layer.rb"; require "test/test_mapnik_raster_colorizer.rb"; require "test/test_mapnik_projection.rb"; require "test/test_mapnik_datasource.rb"; require "test/test_mapnik_style.rb"; require "test/test_mapnik_point_symbolizer.rb"; require "test/test_mapnik_text_symbolizer.rb"; require "test/test_mapnik_rule.rb"; require "test/test_mapnik_stroke.rb"; require "test/test_mapnik_polygon_symbolizer.rb"; require "test/test_mapnik_feature.rb"; require "test/test_mapnik_shield_symbolizer.rb"; require "test/test_mapnik_symbolizer.rb"; require "test/test_polygon_pattern_symbolizer.rb"; require "test/test_line_pattern_symbolizer.rb"; require "test/test_mapnik_raster_symbolizer.rb"; require "test/test_mapnik_coord.rb"; require "test/test_ruby_mapnik.rb"; require "test/test_helper.rb"; require "test/test_mapnik_expression.rb"; require "test/test_mapnik_markers_symbolizer.rb"' -- 
/home/mateusz/Desktop/tmp/Ruby-Mapnik/lib/ruby_mapnik/ruby_mapnik.so: warning: method redefined; discarding old initialize
/home/mateusz/Desktop/tmp/Ruby-Mapnik/lib/ruby_mapnik/ruby_mapnik.so: warning: method redefined; discarding old initialize
/home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_map.rb:58: warning: assigned but unused variable - scale_before
/home/mateusz/.gem/ruby/1.9.1/gems/chunky_png-1.3.4/lib/chunky_png/color.rb:592: warning: assigned but unused variable - min
/home/mateusz/.gem/ruby/1.9.1/gems/chunky_png-1.3.4/lib/chunky_png/canvas/png_decoding.rb:395: warning: assigned but unused variable - line_no
/home/mateusz/.gem/ruby/1.9.1/gems/chunky_png-1.3.4/lib/chunky_png/canvas/operations.rb:269: warning: assigned but unused variable - rotated
/home/mateusz/.gem/ruby/1.9.1/gems/chunky_png-1.3.4/lib/chunky_png/canvas/drawing.rb:302: warning: shadowing outer local variable - y
/home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_layer.rb:10: warning: assigned but unused variable - layer
/home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_layer.rb:34: warning: assigned but unused variable - srs_before
Run options: --seed 16667

# Running tests:

..........................................EEEE................................EE....................................Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: converting 'mode=normal' to 'comp-op:src_over'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: could not convert mode 'grain_merge' into comp-op, defaulting to 'comp-op:src-over'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: could not convert mode 'grain_merge2' into comp-op, defaulting to 'comp-op:src-over'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: converting 'mode:multiply' to 'comp-op:multiply'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: converting 'mode:multiply2' to 'comp-op:multiply'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: could not convert mode 'divide' into comp-op, defaulting to 'comp-op:src-over'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: could not convert mode 'divide2' into comp-op, defaulting to 'comp-op:src-over'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: converting 'mode:screen' to 'comp-op:screen'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-05-14 10:51:34: could not convert mode 'hard_light' into comp-op, defaulting to 'comp-op:src-over'
Mapnik LOG> 2015-05-14 10:51:34: getting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
...............E......................................E................................

Finished tests in 0.154009s, 1318.1036 tests/s, 3097.2187 assertions/s.

  1) Error:
test_should_add_a_geometry(TestMapnikFeature):
ArgumentError: Unable to convert Fixnum to long long
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:23:in `initialize'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:23:in `new'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:23:in `test_should_add_a_geometry'

  2) Error:
test_should_instantiate(TestMapnikFeature):
ArgumentError: Unable to convert Fixnum to long long
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:7:in `initialize'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:7:in `new'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:7:in `test_should_instantiate'

  3) Error:
test_should_return_its_envelope(TestMapnikFeature):
ArgumentError: Unable to convert Fixnum to long long
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:18:in `initialize'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:18:in `new'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:18:in `test_should_return_its_envelope'

  4) Error:
test_should_return_number_of_geometries(TestMapnikFeature):
ArgumentError: Unable to convert Fixnum to long long
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:13:in `initialize'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:13:in `new'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_feature.rb:13:in `test_should_return_number_of_geometries'

  5) Error:
test_should_load_from_file(TestMapnikMap):
ArgumentError: Unable to convert  to mapnik::Map*
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/lib/ruby_mapnik/mapnik/map.rb:107:in `__load_map__'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/lib/ruby_mapnik/mapnik/map.rb:107:in `from_file'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_map.rb:182:in `test_should_load_from_file'

  6) Error:
test_should_load_from_file_path_string(TestMapnikMap):
ArgumentError: Unable to convert  to mapnik::Map*
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/lib/ruby_mapnik/mapnik/map.rb:107:in `__load_map__'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/lib/ruby_mapnik/mapnik/map.rb:107:in `from_file'
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_map.rb:175:in `test_should_load_from_file_path_string'

  7) Error:
test_should_get_and_set_force_odd_labels(TestMapnikShieldSymbolizer):
NoMethodError: undefined method `force_odd_labels=' for #<Mapnik::ShieldSymbolizer:0x8b9f778>
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_shield_symbolizer.rb:70:in `test_should_get_and_set_force_odd_labels'

  8) Error:
test_should_get_and_set_force_odd_labels(TestMapnikTextSymbolizer):
NoMethodError: undefined method `force_odd_labels=' for #<Mapnik::TextSymbolizer:0x8bf5588>
    /home/mateusz/Desktop/tmp/Ruby-Mapnik/test/test_mapnik_text_symbolizer.rb:85:in `test_should_get_and_set_force_odd_labels'

203 tests, 477 assertions, 0 failures, 8 errors, 0 skips
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.9.1 -w -Ilib:bin:test:. -e ...]
/home/mateusz/.gem/ruby/1.9.1/gems/hoe-3.13.1/lib/hoe/test.rb:83:in `block in define_test_tasks'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by gravitystorm** [comment]
OK, that matches what I've got in my new isolated development setup. I think these errors need to be worked through and fixed, i.e. they are genuine errors rather than indicating problems with the installation environment.

I've fixed the first of these failing tests in 9f8f5658e8221c
